---
- hosts: undercloud
  remote_user: stack
  become: false
  collections:
    - tripleo.operator
  roles:
    - ansible-config_template
  vars:
    install_debug: 'true'
    install_ceph_ansible: true

  tasks:
    - name: Install tripleoclient
      block:
        - name: install python2 tripleoclient
          yum:
            name: python-tripleoclient
            state: installed
          become: true
          when: ansible_distribution_major_version|int <= 7

        - name: install python3 tripleoclient
          package:
            name: python3-tripleoclient
            state: present
          become: true
          when: ansible_distribution_major_version|int >= 8

    - name: Install ceph-ansible
      yum:
        name: ceph-ansible
        state: present
      become: true
      when: install_ceph_ansible|bool

    - name: Copy the undercloud config file
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        owner: stack
        group: stack
        mode: 0644
      with_items:
        - undercloud.conf
        - containers-prepare-parameter.yaml

    - name: Trust to the classroom CA
      become: true
      block:
        - name: Fetch the classroom CA certificate
          get_url:
            url: http://classroom.example.com/ca.crt
            dest: /etc/pki/ca-trust/source/anchors/classroom.example.com.crt
            owner: root
            group: root
            mode: '0644'

        - name: Update CA trust
          shell: /bin/update-ca-trust

    - name: Install undercloud
      include_role:
        name: tripleo_undercloud_install
      vars:
        tripleo_undercloud_install_debug: "{{ install_debug }}"

